buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        maven { url = 'https://plugins.gradle.org/m2/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public' }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath group: "org.spongepowered", name: "mixingradle", version: "${mixingradle_version}"
        classpath group: 'org.parchmentmc', name: 'librarian', version: '1.+'
    }
}


plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    // Publishing
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id "com.modrinth.minotaur" version "2.+"
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'org.spongepowered.mixin'

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

version = "${mod_version}"
group = "${mod_group_id}"

base {
    archivesName = mod_id + "-forge"
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name "Sonatype Snapshots"
        url "https://s01.oss.sonatype.org/content/repositories/snapshots/"
    }
    maven {
        url 'https://jitpack.io'
    }
    maven {
        url "https://notalpha.dev/maven/releases"
    }
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${modid}" {
                    source sourceSets.main
                }
            }

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            // should be analogue for any other runs you have
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${modid}" {
                    source sourceSets.main
                }
            }
        }

        data {
            // example of overriding the workingDirectory set in configureEach above
            workingDirectory project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"

}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // TODO jákob if you need modmenu uncomment this and in gradle.properties - !alpha
    // modImplementation "com.terraformersmc:modmenu:$project.modmenu_version"

//    implementation "dev.quantumfusion:Hyphen:0.4.0-rc.3"
    minecraftLibrary  "dev.quantumfusion:Hyphen:0.4.0-rc.3"

//    implementation "dev.notalpha:Taski:2.1.0"
    minecraftLibrary  "dev.notalpha:Taski:2.1.0"

//    implementation 'com.github.luben:zstd-jni:1.5.2-2'
    minecraftLibrary  'com.github.luben:zstd-jni:1.5.2-2'

//    modCompileOnly fabricApi.module("fabric-renderer-indigo", project.fabric_version)
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version       : forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1', // We are version 1 of ourselves
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    // This is the preferred method to reobfuscate your jar file
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"

    // Minecraft 1.17 (21w19a) upwards uses Java 16.
    it.options.release = 17
}

java {
    //include sources in maven publish
    withSourcesJar()
}

//tasks.register('sourcesJar', Jar) {
//    archiveClassifier.set('sources')
//    from sourceSets.main.allJava
//}

// Publishing
/*modrinth {
    token = project.hasProperty("modrinthApiKey") ? project.modrinthApiKey : ""
    projectId = 'ZfQ3kTvR'
    changelog = file("changelog.md").getText()
    versionNumber = project.version
    versionName = "$project.version".split("\\+")[0] + " for $project.minecraft_version"
    uploadFile = remapJar
    versionType = "beta"
    gameVersions = ['1.20', '1.20.1']
    loaders = ['fabric', 'quilt']
}

curseforge {
    apiKey = project.hasProperty("curseForgeApiKey") ? project.curseForgeApiKey : ""
    project {
        id = '472772'
        changelogType = "markdown"
        changelog = file("changelog.md")
        releaseType = 'beta'

        addGameVersion "1.20"
        addGameVersion "1.20.1"
        addGameVersion "Fabric"
        addGameVersion "Quilt"
        addGameVersion "Java 17"

        mainArtifact(remapJar) {
            displayName = "$project.version".split("\\+")[0] + " for $project.minecraft_version"
        }
    }
    options {
        forgeGradleIntegration = false
    }
}*/

tasks.register("publishMod") {
    dependsOn 'modrinth'
    dependsOn 'curseforge'
}

tasks.register("getVersion") {
    print("$project.version")
}

publishing {
    repositories {
        maven {
            name = "notalpha"
            url = "https://notalpha.dev/maven/releases"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

shadowJar {
    configurations = [project.configurations.runtimeClasspath]
}
